// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siykuyewbiqzgtjngqrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpeWt1eWV3Ymlxemd0am5ncXJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1Mjk2NDEsImV4cCI6MjA3NDEwNTY0MX0.XjbDZQEqL52BZ3GvAau6EJuz-4AcRVAfzFi27Esro5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});